// src/pages/Lovebomb.tsx
import React, { useState } from "react";
import { addDoc, collection } from "firebase/firestore";
import { db } from "../firebase/firebase";
import styles from "./Lovebomb.module.css";

const emails = [
  "andreas.ljungstrom@alster.se",
  "anna.nord@alster.se",
  "astrid.taberman@alster.se",
  "benjamin.christ@alster.se",
  "christer.svensson@alster.se",
  "eric.nilsson@alster.se",
  "erik.wadman@alster.se",
  "fredrik.berglund@alster.se",
  "fredrik.jakobsson@alster.se",
  "fredrik.wetterholm@alster.se",
  "henrik.ganheim@alster.se",
  "jim.lofgren@alster.se",
  "joakim.carlsson@alster.se",
  "john.persson@alster.se",
  "jon.hammer@alster.se",
  "jonas.andersson@alster.se",
  "jonas.turnbull@alster.se",
  "karl.mork@alster.se",
  "karolina.sjostrand@alster.se",
  "kevin.candlert@alster.se",
  "kristoffer.karlsson@alster.se",
  "linda.cnattingius@alster.se",
  "louise.hvarfner@alster.se",
  "magnus.olsson@alster.se",
  "malin.nordlund@alster.se",
  "marcus.ahlstrom@alster.se",
  "marta.ballardini@alster.se",
  "martin.lind@alster.se",
  "mathias.petersen@alster.se",
  "matilda.rask@alster.se",
  "mats-hjalmar.murman@alster.se",
  "moa.wetterdal@alster.se",
  "niklas.karlsson@alster.se",
  "per.jaakonantti@alster.se",
  "philip.fryklund@alster.se",
  "rasmus.graham@alster.se",
  "robin.kammerlander@alster.se",
  "stefan.jansson@alster.se",
  "tobias.bergdahl@alster.se",
  "tobias.lendel@alster.se",
  "tommi.ojaskivi@alster.se",
  "veronika.ekstrom@alster.se",
];

const names = emails.map((email) => {
  const name = email.split("@")[0];
  const firstName = name.split(".")[0].replace(/^\w/, (c) => c.toUpperCase());
  const lastName = name.split(".")[1].replace(/^\w/, (c) => c.toUpperCase());
  return `${firstName} ${lastName[0]}`;
});

const Lovebomb: React.FC = () => {
  const [stage, setStage] = useState(0);
  const [shuffledNames, setShuffledNames] = useState<string[]>([]);
  const [name, setName] = useState("");
  const [text, setText] = useState("");

  const shuffleArray = (namesList: string[]) => {
    const list = [...namesList];
    for (let i = list.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [list[i], list[j]] = [list[j], list[i]];
    }
    return list;
  };

  const handleRandomize = () => {
    setText("");
    const randomIndex = Math.floor(Math.random() * names.length);
    const selectedName = names[randomIndex];
    setName(selectedName);
    setStage((prev) => prev + 1); // 0 -> 1

    const newShuffled = shuffleArray(names);
    newShuffled[2] = selectedName; // Ensure the name is at index 2 (or wherever appropriate for display)
    setShuffledNames(newShuffled);

    setTimeout(() => {
      setStage((prev) => prev + 1); // 1 -> 2
    }, 3500);
  };

  const handleOnSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      await addDoc(collection(db, "notes"), {
        name,
        text,
        time: new Date().getTime(),
      });
    } catch {
      console.log("error");
    }
    setStage((prev) => prev + 1); // 2 -> 3
  };

  const handleRestart = () => {
    setStage(0);
    handleRandomize();
  };

  return (
    <section className={styles.section}>
      {stage === 0 && (
        <>
          <button
            className={styles.randomNameBtn}
            onClick={handleRandomize}
          ></button>
          <span className={styles.btnText}>Slumpa fram namn</span>
        </>
      )}

      {stage === 1 && (
        <div className={styles.wrapper}>
          <div className={styles.heart}>
            <ul className={styles.listSpinner}>
              {shuffledNames.map((n, i) => (
                <li key={i} className={styles.spinnerItem}>
                  {n}
                </li>
              ))}
            </ul>
            <span className={styles.chosenName}>{name}</span>
          </div>
        </div>
      )}

      {stage === 2 && (
        <div className={styles.wrapper}>
          <div className={`${styles.heart} ${styles.stage2}`}>
            <span className={`${styles.chosenName} ${styles.stage2Name}`}>
              {name}
            </span>
          </div>
          <form onSubmit={handleOnSubmit} className={styles.form}>
            <label>Skriv nåt du uppskattar med {name}</label>
            <input
              autoFocus
              type="text"
              value={text}
              onChange={(e) => setText(e.target.value)}
              className={styles.input}
            />
            <button type="submit" className={styles.submitBtn}>
              Skicka
            </button>
          </form>
        </div>
      )}

      {stage === 3 && (
        <div className={styles.thanks}>
          <p>Tack för att du lovebombade {name}</p>
          <button onClick={handleRestart} className={styles.restartBtn}>
            Jag har mer kärlek att ge
          </button>
        </div>
      )}
    </section>
  );
};

export default Lovebomb;

// src-svelte/routes/lovebomb/+page.svelte
<script lang="ts">
  import { db } from "../../lib/firebase/firebase";
  import { addDoc, collection } from "firebase/firestore";

  let text = "";
  const emails = [
    "andreas.ljungstrom@alster.se",
    "anna.nord@alster.se",
    "astrid.taberman@alster.se",
    "benjamin.christ@alster.se",
    "christer.svensson@alster.se",
    "eric.nilsson@alster.se",
    "erik.wadman@alster.se",
    "fredrik.berglund@alster.se",
    "fredrik.jakobsson@alster.se",
    "fredrik.wetterholm@alster.se",
    "henrik.ganheim@alster.se",
    "jim.lofgren@alster.se",
    "joakim.carlsson@alster.se",
    "john.persson@alster.se",
    "jon.hammer@alster.se",
    "jonas.andersson@alster.se",
    "jonas.turnbull@alster.se",
    "karl.mork@alster.se",
    "karolina.sjostrand@alster.se",
    "kevin.candlert@alster.se",
    "kristoffer.karlsson@alster.se",
    "linda.cnattingius@alster.se",
    "louise.hvarfner@alster.se",
    "magnus.olsson@alster.se",
    "malin.nordlund@alster.se",
    "marcus.ahlstrom@alster.se",
    "marta.ballardini@alster.se",
    "martin.lind@alster.se",
    "mathias.petersen@alster.se",
    "matilda.rask@alster.se",
    "mats-hjalmar.murman@alster.se",
    "moa.wetterdal@alster.se",
    "niklas.karlsson@alster.se",
    "per.jaakonantti@alster.se",
    "philip.fryklund@alster.se",
    "rasmus.graham@alster.se",
    "robin.kammerlander@alster.se",
    "stefan.jansson@alster.se",
    "tobias.bergdahl@alster.se",
    "tobias.lendel@alster.se",
    "tommi.ojaskivi@alster.se",
    "veronika.ekstrom@alster.se",
  ];
  const names = emails.map((email) => {
    const name = email.split("@")[0];
    const firstName = name.split(".")[0].replace(/^\w/, (c) => c.toUpperCase());
    const lastName = name.split(".")[1].replace(/^\w/, (c) => c.toUpperCase());
    return `${firstName} ${lastName.charAt(0)}`;
  });

  let shuffledNames: string[] = [];
  let name = "";
  let randomIndex = 0;
  let stage = 0;

  const handleRandomize = () => {
    text = "";
    randomIndex = Math.floor(Math.random() * names.length);
    name = names[randomIndex];
    stage++;

    shuffledNames = shuffleArray(names);
    shuffledNames[2] = name;

    setTimeout(() => {
      stage++;
    }, 3500);
  };

  const shuffleArray = (namesList: string[]) => {
    for (let i = namesList.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [namesList[i], namesList[j]] = [namesList[j], namesList[i]];
    }
    return namesList;
  };

  const handleOnSubmit = async () => {
    try {
      await addDoc(collection(db, "notes"), {
        name,
        text,
        time: new Date().getTime(),
      });
    } catch {
      console.log("error");
    }
    stage++;
  };

  const handleRestart = () => {
    stage = 0;
    handleRandomize();
  };
</script>

<section>
  {#if stage === 0}
    <button class="random-name-btn" on:click={handleRandomize}></button>
    <span class="btn-text">Slumpa fram namn</span>
  {:else if stage === 1}
    <div class="wrapper">
      <div class="heart">
        <ul class="list-spinner">
          {#each shuffledNames as n}
            <li>{n}</li>
          {/each}
        </ul>
        <span class="chosen-name">{name}</span>
      </div>
    </div>
  {:else if stage === 2}
    <div class="wrapper">
      <div class="heart stage-2">
        <span class="chosen-name stage-2">{name}</span>
      </div>
      <form on:submit={handleOnSubmit}>
        <label>Skriv nåt du uppskattar med {name}</label>
        <input autofocus type="text" bind:value={text} />
        <button type="submit">Skicka</button>
      </form>
    </div>
  {:else}
    <div class="thanks">
      <p>Tack för att du lovebombade {name}</p>
      <button on:click={handleRestart}>Jag har mer kärlek att ge</button>
    </div>
  {/if}
</section>

<style>
  section {
    width: 100vw;
    height: 100vh;
    display: flex;
    justify-content: center;
    align-items: center;
  }

  .random-name-btn,
  .heart {
    color: #fda4ff;
    background-color: transparent;
    border: none;
    background-image: url("/heart.svg");
    background-size: contain;
    background-repeat: no-repeat;
    height: 70vw;
    width: 70vw;
    max-height: 500px;
    max-width: 500px;
    animation: beatingHeart 1s infinite;
    mask-image: url("/heart.svg");
    mask-size: contain;
    mask-repeat: no-repeat;
    mask-position: center;
    -webkit-mask-image: url("/heart.svg");
    -webkit-mask-size: contain;
    -webkit-mask-repeat: no-repeat;
    -webkit-mask-position: center;
    position: relative;
  }

  .heart.stage-2 {
    display: flex;
    justify-content: center;
    align-items: center;
    animation: none;
    animation: moveHeart 1s;
    position: absolute;
    transform: scale(0.8) translateY(-250px);
  }

  .btn-text {
    position: absolute;
    top: 48vh;
    color: white;
    text-transform: uppercase;
    pointer-events: none;
    font-size: 4vw;
  }

  .list-spinner {
    height: 100%;
    width: 100%;
    overflow: hidden;
    position: absolute;
    list-style-type: none;
    padding-left: 0;
    padding-top: 1.7vw; /* Align index 2 with chosenName */
    font-size: 8vw;
    text-align: center;
    color: #fcddff;
    /* color: white; */
    text-transform: uppercase;
    top: 0;
    left: 0;
    right: 0;
    margin: 0 auto;
    white-space: nowrap;
  }

  li {
    height: 10vw;
    line-height: 10vw;
    animation: spinLi 2s;
    opacity: 0;
    transition-timing-function: cubic-bezier(0, 1.15, 0, 0.9);
  }

  .chosen-name {
    position: absolute;
    color: white;
    text-transform: uppercase;
    font-size: 8vw;
    animation: showChosen 2s;
    top: 38.1%;
    margin-left: auto;
    margin-right: auto;
    left: 0;
    right: 0;
    text-align: center;
    color: white;
  }

  .chosen-name.stage-2 {
    position: relative;
    animation: none;
    top: -3.5vw;
  }

  .wrapper {
    position: relative;
    display: flex;
    justify-content: center;
    align-items: center;
  }

  form {
    font-size: 1.5rem;
    text-align: center;
    padding: 50px;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    gap: 10px;
  }
  input {
    width: 100%;
    height: 50px;
    border: none;
    outline: none;
    color: var(--dark-burgundy);
    font-family: var(--main-font);
    font-size: 1rem;
    text-align: center;
  }
  button[type="submit"],
  .thanks button {
    width: calc(100% + 4px);
    height: 50px;
    border: none;
    color: white;
    background-color: #fda4ff;
    text-transform: uppercase;
    font-family: var(--main-font);
    font-size: 1rem;
  }

  .thanks {
    display: flex;
    flex-direction: column;
    padding: 50px;
    text-align: center;
  }

  .thanks p {
    font-size: 2rem;
    margin-top: -40px;
  }

  @keyframes beatingHeart {
    0% {
      transform: scale(1);
    }

    50% {
      transform: scale(1.2);
    }

    100% {
      transform: scale(1);
    }
  }

  @keyframes spinLi {
    0% {
      transform: translateY(-200vh);
      opacity: 1;
    }

    95% {
      opacity: 1;
      transform: translateY(0);
    }

    100% {
      opacity: 0;
    }
  }

  @keyframes showChosen {
    0% {
      opacity: 0;
    }

    90% {
      opacity: 0;
    }

    100% {
      opacity: 1;
    }
  }

  @keyframes moveHeart {
    from {
      transform: scale(1);
    }
    to {
      transform: scale(0.8) translateY(-250px);
    }
  }
</style>
